-- MySQL Script generated by MySQL Workbench
-- Sun May 11 14:07:57 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_cafeteria
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_cafeteria
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_cafeteria` DEFAULT CHARACTER SET utf8 ;
USE `db_cafeteria` ;

-- -----------------------------------------------------
-- Table `db_cafeteria`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cafeteria`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(50) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) ,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) );


-- -----------------------------------------------------
-- Table `db_cafeteria`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cafeteria`.`orders` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `description` VARCHAR(300) NULL,
  `is_paid` BIT(1) NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `fk_pedidos_usuarios1_idx` (`id_user` ASC) ,
  CONSTRAINT `fk_pedidos_usuarios1`
    FOREIGN KEY (`id_user`)
    REFERENCES `db_cafeteria`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cafeteria`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cafeteria`.`products` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NOT NULL,
  `product_price` FLOAT NOT NULL,
  `is_unlimited` BIT(1) NOT NULL,
  `url_image` VARCHAR(255) NULL,
  `product_description` VARCHAR(255) NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cafeteria`.`orders_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cafeteria`.`orders_has_products` (
  `id_order` INT NOT NULL,
  `id_product` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`id_order`, `id_product`),
  INDEX `fk_pedidos_has_productos_productos1_idx` (`id_product` ASC) ,
  INDEX `fk_pedidos_has_productos_pedidos1_idx` (`id_order` ASC) ,
  CONSTRAINT `fk_pedidos_has_productos_pedidos1`
    FOREIGN KEY (`id_order`)
    REFERENCES `db_cafeteria`.`orders` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedidos_has_productos_productos1`
    FOREIGN KEY (`id_product`)
    REFERENCES `db_cafeteria`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cafeteria`.`authorities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cafeteria`.`authorities` (
  `users_id_user` INT NOT NULL,
  `authorities` ENUM('ADMIN', 'SYSTEM', 'USER') NOT NULL,
  INDEX `fk_authorities_users1_idx` (`users_id_user` ASC) ,
  PRIMARY KEY (`users_id_user`, `authorities`),
  CONSTRAINT `fk_authorities_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `db_cafeteria`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cafeteria`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cafeteria`.`cart` (
  `id_cart` INT NOT NULL AUTO_INCREMENT,
  `users_id_user` INT NOT NULL,
  INDEX `fk_CART_users1_idx` (`users_id_user` ASC) ,
  PRIMARY KEY (`id_cart`),
  CONSTRAINT `fk_CART_users1`
    FOREIGN KEY (`users_id_user`)
    REFERENCES `db_cafeteria`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cafeteria`.`cart_has_products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cafeteria`.`cart_has_products` (
  `products_id_product` INT NOT NULL,
  `CART_id_cart` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`products_id_product`, `CART_id_cart`),
  INDEX `fk_products_has_CART_CART1_idx` (`CART_id_cart` ASC) ,
  INDEX `fk_products_has_CART_products1_idx` (`products_id_product` ASC) ,
  CONSTRAINT `fk_products_has_CART_products1`
    FOREIGN KEY (`products_id_product`)
    REFERENCES `db_cafeteria`.`products` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_products_has_CART_CART1`
    FOREIGN KEY (`CART_id_cart`)
    REFERENCES `db_cafeteria`.`cart` (`id_cart`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_cafeteria`.`orderState`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_cafeteria`.`orderState` (
  `orders_id_order` INT NOT NULL,
  `state` ENUM("PENDIENTE", "FINALIZADO") NOT NULL,
  INDEX `fk_orderState_orders1_idx` (`orders_id_order` ASC) ,
  PRIMARY KEY (`orders_id_order`),
  CONSTRAINT `fk_orderState_orders1`
    FOREIGN KEY (`orders_id_order`)
    REFERENCES `db_cafeteria`.`orders` (`id_order`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
